set nocompatible
set nobackup
set nowritebackup
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
filetype off

let vundle_install=!filereadable(expand('~/.vim/bundle/vundle/README.md'))
if vundle_install
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
endif

set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

Plugin 'gmarik/vundle'
Plugin 'chriskempson/base16-vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'

call vundle#end()

if vundle_install
    silent PluginInstall
endif

set shiftwidth=4 expandtab
filetype plugin indent on
syntax on
set backspace=indent,eol,start
let base16colorspace=256
set background=dark
colorscheme base16-tomorrow
hi Normal ctermbg=none
hi DiffAdd ctermbg=none
hi DiffChange ctermbg=none
hi DiffDelete ctermbg=none
hi DiffText ctermbg=none
hi DiffAdded ctermbg=none
hi DiffFile ctermbg=none
hi DiffNewFile ctermbg=none
hi DiffLine ctermbg=none
hi DiffRemoved ctermbg=none
hi MatchParen ctermfg=none ctermbg=04
set incsearch
set smartcase
