set nocompatible
set nobackup
set nowritebackup
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set shiftwidth=2 expandtab

filetype plugin indent on
syntax on

set runtimepath=~/.dotfiles/vim,$VIMRUNTIME
let base16colorspace=256
set background=dark
colorscheme base16-tomorrow
