set nocompatible
set nobackup
set nowritebackup
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set shiftwidth=2 expandtab
set number
set relativenumber
set numberwidth=5
set laststatus=2
set cursorline
set statusline=%1*%<%t\ %m%=%{&ff}\ \|\ %l:%2v\ \ %P%*

filetype plugin indent on
syntax on

set runtimepath=~/.dotfiles/vim,$VIMRUNTIME
let base16colorspace=256
set background=dark
colorscheme base16-tomorrow-night
